#!/bin/bash
echo "=== Script de Ayuda para Despliegue de MVP ==="
echo "Este script asume que ya ejecutaste 'terraform apply' en la carpeta infraestructura."

# Reemplaza esto con tu IP publica de EC2 y nombre de bucket
EC2_IP="TU_IP_PUBLICA_EC2"
BUCKET_NAME="hito1-bucket" # o el nombre que hayas puesto en variables.tf

echo ""
echo "1. DESPLIEGUE DEL FRONTEND (S3)"
echo "--------------------------------"
echo "Para desplegar el frontend, ejecuta los siguientes comandos desde la raíz del proyecto:"
echo "cd frontend"
echo "npm run build"
echo "aws s3 sync dist/ s3://$BUCKET_NAME --delete"
echo "*(Asegúrate de que tu bucket tenga los permisos para servir Static Website Hosting)*"
echo ""

echo "2. DESPLIEGUE DEL BACKEND (EC2 - NGINX + Node.js)"
echo "------------------------------------------------"
echo "Para desplegar el backend, conéctate a tu instancia EC2 por SSH:"
echo "ssh -i tu_llave.pem ec2-user@$EC2_IP"
echo ""
echo "Luego, ejecuta estos comandos dentro de la instancia EC2 para configurar el entorno robusto:"
echo ""
echo "# Instalar dependencias base"
echo "sudo dnf update -y"
echo "sudo dnf install -y nginx nodejs"
echo ""
echo "# Instalar PM2 para mantener Node.js corriendo"
echo "sudo npm install -g pm2"
echo ""
echo "# Copiar tu código backend al servidor (puedes usar scp o git clone)"
echo "# Una vez en la carpeta backend de tu EC2, instala dependencias e inicia pm2:"
echo "npm install"
echo "pm2 start server.js --name unireports-api"
echo "pm2 save"
echo "pm2 startup"
echo ""
echo "# Configurar NGINX como reverse proxy"
echo "sudo rm /etc/nginx/conf.d/default.conf"
echo "sudo tee /etc/nginx/conf.d/api.conf > /dev/null <<EOF"
echo "server {"
echo "    listen 80;"
echo "    server_name _;"
echo ""
echo "    location /api/ {"
echo "        proxy_pass http://localhost:3000/api/;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Upgrade \\\$http_upgrade;"
echo "        proxy_set_header Connection 'upgrade';"
echo "        proxy_set_header Host \\\$host;"
echo "        proxy_cache_bypass \\\$http_upgrade;"
echo "    }"
echo "}"
echo "EOF"
echo ""
echo "# Reiniciar NGINX"
echo "sudo systemctl enable nginx"
echo "sudo systemctl restart nginx"
echo ""
echo "¡Tu backend estará respondiendo en http://$EC2_IP/api/ y tu frontend en el bucket de S3!"
